### ISSUE TITLE
Build fails if no .go files located at root

### ISSUE THREAD

**Issue by sabre1041** [sclorg/golang-container#15]
A common patten for golang projects are to have the `main` package within the `<cmd>/<binary>` folder with no `.go` files located in the project root. This causes a failure when attempting to perform an S2I build as the `go list -f {{.Incomplete}}` command fails.

**Comment by jcajka** [comment]
Set the INSTALL_URL for more read https://github.com/sclorg/golang-container/tree/master/1.11#environment-variables
Hm... maybe there could be better error message. Could you please attach log of the build?

**Comment by jcajka** [comment]
There is new pull request with better error message.

**Comment by jcajka** [comment]
@sabre1041 Just for the record without the INSTALL_URL, assemble script has no sensible way how to infer what are you trying to build(there might be more binaries, etc.).
