### ISSUE TITLE
Docker hub has only Go 1.10 image

### ISSUE THREAD

**Issue by jarifibrahim** [sclorg/golang-container#16]
The repository https://hub.docker.com/r/centos/go-toolset-7-centos7/ has only one image which contains Go 1.10. It should have all the supported versions of Go.

**Comment by jcajka** [comment]
This is not related to this repo. Please open issue in CentOS issue tracker, but keep in mind that downstream distribution mostly only support subset(some times supper set, but I haven't see that in Go world) of the upstream supported versions.

**Comment by omron93** [comment]
> Please open issue in CentOS issue tracker

Docker Hub is used for CentOS based images rebuilded from RedHat Devtools channel. RedHat released only go 1.10 now [1]. To request some new versions, please report bug in http://bugzilla.redhat.com/

About golang from this repository: you can use Fedora based images to be able to choose whatever golang version from this repo. Fedora images are pushed into registry.fedoraproject.org and mapping of golang version to fedora version can be found in https://apps.fedoraproject.org/packages/golang

So for example to get image with golang 1.11 you can use **registry.fedoraproject.org/f29/golang** image.


[1] https://developers.redhat.com/blog/2018/11/13/clang-llvm-6-0-go-1-10-and-rust-1-29-now-ga-for-rhel/

**Comment by jarifibrahim** [comment]
Thanks @omron93 and @jcajka :)
