### ISSUE TITLE
Use better assemble script

### ISSUE THREAD

**Issue by jarifibrahim** [sclorg/golang-container#17]
The assemble script used currently supports very limited features. We should improve the assemble script and build something similar to https://github.com/amsokol/openshift-golang-template/blob/master/S2I/.s2i/bin/assemble

**Comment by jcajka** [comment]
What feature are you missing/wanting?

**Comment by jarifibrahim** [comment]
For starters 
 - it should support package managers. I've raised https://github.com/sclorg/golang-container/pull/19 to add support for dep.

 - I also found the `IMPORT_URL` and `INSTALL_URL` confusing. I still don't know why do I need those. Maybe we should update the docs?

 - The script didn't work for me when I tried it. See https://github.com/sclorg/golang-container/issues/18
Not sure what went wrong.

**Comment by jcajka** [comment]
@jarifibrahim I'm generally against pulling in dependencies(yet more tools) via go get/wget/... in to the base image as it is not reproducible and most importantly are incompatible with distro infras/guidelines/philosophy, so it is no go. I think that you would be better of with your own layered image for this or you will need to package those tools for distributions that you are interested in(and we will pull them in via yum or dnf). AFAIK dep is dead and has been replaced with Go modules(which we should support as it is part of the base toolset from go1.11). I want to look in to the modules support, but I haven't go time for that yet.

What is not clear? In generally(in addition to what is written in the README) those are needed as there is/were no canonical repo layout for Go package(in asme way as for C/C++ project). And many are using complex build scripts.

I will investigate.

Closing this as you have opened issues that are actually actionable and concrete.

**Comment by jarifibrahim** [comment]
>I think that you would be better of with your own layered image for this 

Do you mean using a different builder image than `go-toolset-7-centos7`?

**Comment by jcajka** [comment]
> > I think that you would be better of with your own layered image for this
> 
> Do you mean using a different builder image than `go-toolset-7-centos7`?

No that you will create your own builder image ```FROM go-toolset-7-centos7 ``` and you will add and override what you will need(install dep, use your own assemble/build script,...). Image from this repo aim on providing only thing that could be supported(whatever that means) by the respective distro, i.e. are not randomly pulled from internet.

**Comment by sbose78** [comment]
> AFAIK dep is dead and has been replaced with Go modules
`dep` is still used heavily in a lot of projects, and adding support for it will make this builder image useful.
